"Список категорий Category (Code)"
"Список параметров в каждой (Categ_Code, Param_Code)" 
"Формула подсчета каждого параметра Formula (Param_Code, Test_Code, Formula_Text) Example (- 24 (* 5 (+ (Q10 V3) (Q11 V2)))"
"Таблица параметров Params (Code, Description)"
"Таблица Results (Org_Code, user, Param_Code, Value)"
